-- Supabase Schema for CodeQuest
-- This script is designed to be run once in the Supabase SQL Editor.

-- 1. USERS Table
-- Stores core user information.
CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 2. LANGUAGES Table
-- Defines the programming languages offered on the platform.
CREATE TABLE IF NOT EXISTS public.languages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) UNIQUE NOT NULL,
    icon_svg TEXT -- You can store SVG code for language icons here
);

-- 3. USER_PROGRESS Table
-- Tracks a user's current level in a specific language.
CREATE TABLE IF NOT EXISTS public.user_progress (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    language_id BIGINT NOT NULL REFERENCES public.languages(id) ON DELETE CASCADE,
    current_level INT NOT NULL DEFAULT 1,
    last_updated TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(user_id, language_id) -- Ensures a user has only one progress entry per language
);

-- 4. BADGES Table
-- Defines all possible badges a user can earn.
CREATE TABLE IF NOT EXISTS public.badges (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) UNIQUE NOT NULL,
    description TEXT NOT NULL,
    language_id BIGINT NOT NULL REFERENCES public.languages(id) ON DELETE CASCADE,
    level_required INT NOT NULL,
    icon_url VARCHAR(255) -- Link to an image for the badge
);

-- 5. USER_BADGES Table
-- A linking table that records every badge awarded to each user.
CREATE TABLE IF NOT EXISTS public.user_badges (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    badge_id BIGINT NOT NULL REFERENCES public.badges(id) ON DELETE CASCADE,
    earned_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(user_id, badge_id) -- Ensures a user can't earn the same badge twice
);

-- Optional: Insert initial language data so your application has languages to show
INSERT INTO public.languages (name) VALUES ('Python'), ('C'), ('Java')
ON CONFLICT (name) DO NOTHING;

